// Code generated by MockGen. DO NOT EDIT.
// Source: service/planetmint_client.go

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPlanetmintClient is a mock of IPlanetmintClient interface.
type MockIPlanetmintClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPlanetmintClientMockRecorder
}

// MockIPlanetmintClientMockRecorder is the mock recorder for MockIPlanetmintClient.
type MockIPlanetmintClientMockRecorder struct {
	mock *MockIPlanetmintClient
}

// NewMockIPlanetmintClient creates a new mock instance.
func NewMockIPlanetmintClient(ctrl *gomock.Controller) *MockIPlanetmintClient {
	mock := &MockIPlanetmintClient{ctrl: ctrl}
	mock.recorder = &MockIPlanetmintClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPlanetmintClient) EXPECT() *MockIPlanetmintClientMockRecorder {
	return m.recorder
}

// GetValidatorAddresses mocks base method.
func (m *MockIPlanetmintClient) GetValidatorAddresses() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorAddresses")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorAddresses indicates an expected call of GetValidatorAddresses.
func (mr *MockIPlanetmintClientMockRecorder) GetValidatorAddresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorAddresses", reflect.TypeOf((*MockIPlanetmintClient)(nil).GetValidatorAddresses))
}

// GetValidatorDelegationAddresses mocks base method.
func (m *MockIPlanetmintClient) GetValidatorDelegationAddresses(validatorAddress string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorDelegationAddresses", validatorAddress)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorDelegationAddresses indicates an expected call of GetValidatorDelegationAddresses.
func (mr *MockIPlanetmintClientMockRecorder) GetValidatorDelegationAddresses(validatorAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorDelegationAddresses", reflect.TypeOf((*MockIPlanetmintClient)(nil).GetValidatorDelegationAddresses), validatorAddress)
}
