// Code generated by MockGen. DO NOT EDIT.
// Source: service/r2p_client.go

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIR2PClient is a mock of IR2PClient interface.
type MockIR2PClient struct {
	ctrl     *gomock.Controller
	recorder *MockIR2PClientMockRecorder
}

// MockIR2PClientMockRecorder is the mock recorder for MockIR2PClient.
type MockIR2PClientMockRecorder struct {
	mock *MockIR2PClient
}

// NewMockIR2PClient creates a new mock instance.
func NewMockIR2PClient(ctrl *gomock.Controller) *MockIR2PClient {
	mock := &MockIR2PClient{ctrl: ctrl}
	mock.recorder = &MockIR2PClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIR2PClient) EXPECT() *MockIR2PClientMockRecorder {
	return m.recorder
}

// GetReceiveAddress mocks base method.
func (m *MockIR2PClient) GetReceiveAddress(plmntAddress string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiveAddress", plmntAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceiveAddress indicates an expected call of GetReceiveAddress.
func (mr *MockIR2PClientMockRecorder) GetReceiveAddress(plmntAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiveAddress", reflect.TypeOf((*MockIR2PClient)(nil).GetReceiveAddress), plmntAddress)
}
